
server:
   port: 8888
spring:
  profiles:
    active: native

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/,classpath:config/goodsservice,classpath:config/userservice,classpath:config/orderservice
        encrypt:
          enable: false


logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.springmicroservice: INFO